name: crypt_ui
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  bloc: ^8.1.2
  crypto: ^3.0.3
  cryptography: ^2.5.0
  download: ^1.0.0
  equatable: ^2.0.5
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^8.0.0
  http: ^1.0.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSerifSC
      fonts:
        - asset: assets\fonts\NotoSerifSC-Regular.otf
